name: Run tests
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.11
    - name: Run tests
      run: python -m unittest discover -s test -v
